### ISSUE TITLE
I think this breaks meteor 1.4

### ISSUE THREAD

**Issue by chmac** [studiointeract/accounts-semantic#2]
By trial and error, it seems like when I add this package to a 1.4 meteor project, it breaks meteor, throwing an error about `fourseven:scss`.

The error is:

```
=> Errors while upgrading packages:

While loading package fourseven:scss@3.4.3:
error: Command failed:
...
Error: Cannot find module '../'
```

I read [elsewhere](https://github.com/themeteorchef/bert/commit/2474769430f467a6824288787fe22f1c4c4eb6bb) that there's an issue with scss version `3.3.3_3`, and maybe upgrading to `3.8.0_1` will fix the issue...

**Comment by palatok** [comment]
yes, i found the same issue too.
`While loading package fourseven:scss@3.4.3:
error: Command failed: /Users/palatok/.meteor/packages/meteor-tool/.1.4.0-1.16adoo5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/palatok/.meteor/packages/fourseven_scss/.3.4.3.jjm00q++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-10pfxg4/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/palatok/.meteor/packages/meteor-tool/.1.4.0-1.16adoo5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/palatok/.meteor/packages/meteor-tool/.1.4.0-1.16adoo5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/palatok/.meteor/packages/fourseven_scss/.3.4.3.jjm00q++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-10pfxg4/npm-debug.log
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/Users/palatok/.meteor/packages/fourseven_scss/.3.4.3.jjm00q++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-10pfxg4/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/palatok/.meteor/packages/meteor-tool/.1.4.0-1.16adoo5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/palatok/.meteor/packages/meteor-tool/.1.4.0-1.16adoo5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/palatok/.meteor/packages/fourseven_scss/.3.4.3.jjm00q++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-10pfxg4/npm-debug.log`

**Comment by windgaucho** [comment]
@chmac the same happened to me.

**Comment by palatok** [comment]
same happened to me
